// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/robgonnella/minienv/internal/os"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommander creates a new instance of MockCommander. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommander(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommander {
	mock := &MockCommander{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommander is an autogenerated mock type for the Commander type
type MockCommander struct {
	mock.Mock
}

type MockCommander_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommander) EXPECT() *MockCommander_Expecter {
	return &MockCommander_Expecter{mock: &_m.Mock}
}

// Command provides a mock function for the type MockCommander
func (_mock *MockCommander) Command(name string, args ...string) os.CommandRunner {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 os.CommandRunner
	if returnFunc, ok := ret.Get(0).(func(string, ...string) os.CommandRunner); ok {
		r0 = returnFunc(name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.CommandRunner)
		}
	}
	return r0
}

// MockCommander_Command_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Command'
type MockCommander_Command_Call struct {
	*mock.Call
}

// Command is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockCommander_Expecter) Command(name any, args ...any) *MockCommander_Command_Call {
	return &MockCommander_Command_Call{Call: _e.mock.On("Command",
		append([]any{name}, args...)...)}
}

func (_c *MockCommander_Command_Call) Run(run func(name string, args ...string)) *MockCommander_Command_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCommander_Command_Call) Return(commandRunner os.CommandRunner) *MockCommander_Command_Call {
	_c.Call.Return(commandRunner)
	return _c
}

func (_c *MockCommander_Command_Call) RunAndReturn(run func(name string, args ...string) os.CommandRunner) *MockCommander_Command_Call {
	_c.Call.Return(run)
	return _c
}
