// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandRunner creates a new instance of MockCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandRunner {
	mock := &MockCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandRunner is an autogenerated mock type for the CommandRunner type
type MockCommandRunner struct {
	mock.Mock
}

type MockCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandRunner) EXPECT() *MockCommandRunner_Expecter {
	return &MockCommandRunner_Expecter{mock: &_m.Mock}
}

// Output provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) Output() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandRunner_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type MockCommandRunner_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
func (_e *MockCommandRunner_Expecter) Output() *MockCommandRunner_Output_Call {
	return &MockCommandRunner_Output_Call{Call: _e.mock.On("Output")}
}

func (_c *MockCommandRunner_Output_Call) Run(run func()) *MockCommandRunner_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandRunner_Output_Call) Return(bytes []byte, err error) *MockCommandRunner_Output_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCommandRunner_Output_Call) RunAndReturn(run func() ([]byte, error)) *MockCommandRunner_Output_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockCommandRunner_Expecter) Run() *MockCommandRunner_Run_Call {
	return &MockCommandRunner_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockCommandRunner_Run_Call) Run(run func()) *MockCommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandRunner_Run_Call) Return(err error) *MockCommandRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandRunner_Run_Call) RunAndReturn(run func() error) *MockCommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Stderr provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) Stderr(writer io.Writer) {
	_mock.Called(writer)
	return
}

// MockCommandRunner_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockCommandRunner_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
//   - writer io.Writer
func (_e *MockCommandRunner_Expecter) Stderr(writer any) *MockCommandRunner_Stderr_Call {
	return &MockCommandRunner_Stderr_Call{Call: _e.mock.On("Stderr", writer)}
}

func (_c *MockCommandRunner_Stderr_Call) Run(run func(writer io.Writer)) *MockCommandRunner_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommandRunner_Stderr_Call) Return() *MockCommandRunner_Stderr_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandRunner_Stderr_Call) RunAndReturn(run func(writer io.Writer)) *MockCommandRunner_Stderr_Call {
	_c.Run(run)
	return _c
}

// Stdin provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) Stdin(reader io.Reader) {
	_mock.Called(reader)
	return
}

// MockCommandRunner_Stdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdin'
type MockCommandRunner_Stdin_Call struct {
	*mock.Call
}

// Stdin is a helper method to define mock.On call
//   - reader io.Reader
func (_e *MockCommandRunner_Expecter) Stdin(reader any) *MockCommandRunner_Stdin_Call {
	return &MockCommandRunner_Stdin_Call{Call: _e.mock.On("Stdin", reader)}
}

func (_c *MockCommandRunner_Stdin_Call) Run(run func(reader io.Reader)) *MockCommandRunner_Stdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommandRunner_Stdin_Call) Return() *MockCommandRunner_Stdin_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandRunner_Stdin_Call) RunAndReturn(run func(reader io.Reader)) *MockCommandRunner_Stdin_Call {
	_c.Run(run)
	return _c
}

// Stdout provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) Stdout(writer io.Writer) {
	_mock.Called(writer)
	return
}

// MockCommandRunner_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type MockCommandRunner_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
//   - writer io.Writer
func (_e *MockCommandRunner_Expecter) Stdout(writer any) *MockCommandRunner_Stdout_Call {
	return &MockCommandRunner_Stdout_Call{Call: _e.mock.On("Stdout", writer)}
}

func (_c *MockCommandRunner_Stdout_Call) Run(run func(writer io.Writer)) *MockCommandRunner_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommandRunner_Stdout_Call) Return() *MockCommandRunner_Stdout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandRunner_Stdout_Call) RunAndReturn(run func(writer io.Writer)) *MockCommandRunner_Stdout_Call {
	_c.Run(run)
	return _c
}
