# $schema: ./schema/schema.json

x-minienv:
  k8s:
    context: minikube
    namespace: $MINIENV_NAMESPACE

services:
  hello:
    x-minienv-k8s-service:
      ngrok:
        port: 8080
      env:
        - name: LOG_LEVEL
          value: debug
      image:
        repository: rgonnella/demo-hello
        tag: latest
        platforms:
          - linux/amd64
          - linux/arm64/v8
    build: .
    ports:
      - 8080:8080
    healthcheck:
      test: curl http://localhost:8080
    depends_on:
      job:
        condition: service_completed_successfully

  hello2:
    x-minienv-k8s-service:
      ngrok:
        port: 8080
      service:
        ports:
          - containerPortName: hello
            containerPort: 8080
            protocol: TCP
      image:
        repository: rgonnella/demo-hello
        tag: test-+git
        platforms:
          - linux/amd64
          - linux/arm64/v8
    build: .
    healthcheck:
      test: curl http://localhost:8080
    depends_on:
      postgres:
        condition: service_healthy

  job:
    x-minienv-k8s-service:
      skip: false
      deploymentType: job
    image: alpine:3.24
    command:
      - /bin/sh
      - -c
      - sleep 10 && echo "ready"
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    x-minienv-k8s-service:
      skip: false
      configMapFrom:
        - init/01-schema.sql
      volumes:
        - name: init
          configMap:
            name: postgres
      volumeMounts:
        - name: init
          mountPath: /docker-entrypoint-initdb.d
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -d postgres
