// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transportmocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFile provides a mock function for the type MockClient
func (_mock *MockClient) CreateFile(filepath string, content []byte) error {
	ret := _mock.Called(filepath, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(filepath, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type MockClient_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - filepath string
//   - content []byte
func (_e *MockClient_Expecter) CreateFile(filepath any, content any) *MockClient_CreateFile_Call {
	return &MockClient_CreateFile_Call{Call: _e.mock.On("CreateFile", filepath, content)}
}

func (_c *MockClient_CreateFile_Call) Run(run func(filepath string, content []byte)) *MockClient_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_CreateFile_Call) Return(err error) *MockClient_CreateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateFile_Call) RunAndReturn(run func(filepath string, content []byte) error) *MockClient_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// RunCommand provides a mock function for the type MockClient
func (_mock *MockClient) RunCommand(cmd string) error {
	ret := _mock.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for RunCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RunCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCommand'
type MockClient_RunCommand_Call struct {
	*mock.Call
}

// RunCommand is a helper method to define mock.On call
//   - cmd string
func (_e *MockClient_Expecter) RunCommand(cmd any) *MockClient_RunCommand_Call {
	return &MockClient_RunCommand_Call{Call: _e.mock.On("RunCommand", cmd)}
}

func (_c *MockClient_RunCommand_Call) Run(run func(cmd string)) *MockClient_RunCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_RunCommand_Call) Return(err error) *MockClient_RunCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RunCommand_Call) RunAndReturn(run func(cmd string) error) *MockClient_RunCommand_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockClient
func (_mock *MockClient) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockClient_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockClient_Expecter) String() *MockClient_String_Call {
	return &MockClient_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockClient_String_Call) Run(run func()) *MockClient_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_String_Call) Return(s string) *MockClient_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_String_Call) RunAndReturn(run func() string) *MockClient_String_Call {
	_c.Call.Return(run)
	return _c
}
