// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package imagemocks

import (
	"context"

	"github.com/robgonnella/minienv/internal/image"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BuildAndPush provides a mock function for the type MockClient
func (_mock *MockClient) BuildAndPush(ctx context.Context, services []image.ServiceProperties) error {
	ret := _mock.Called(ctx, services)

	if len(ret) == 0 {
		panic("no return value specified for BuildAndPush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []image.ServiceProperties) error); ok {
		r0 = returnFunc(ctx, services)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_BuildAndPush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildAndPush'
type MockClient_BuildAndPush_Call struct {
	*mock.Call
}

// BuildAndPush is a helper method to define mock.On call
//   - ctx context.Context
//   - services []image.ServiceProperties
func (_e *MockClient_Expecter) BuildAndPush(ctx any, services any) *MockClient_BuildAndPush_Call {
	return &MockClient_BuildAndPush_Call{Call: _e.mock.On("BuildAndPush", ctx, services)}
}

func (_c *MockClient_BuildAndPush_Call) Run(run func(ctx context.Context, services []image.ServiceProperties)) *MockClient_BuildAndPush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []image.ServiceProperties
		if args[1] != nil {
			arg1 = args[1].([]image.ServiceProperties)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_BuildAndPush_Call) Return(err error) *MockClient_BuildAndPush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_BuildAndPush_Call) RunAndReturn(run func(ctx context.Context, services []image.ServiceProperties) error) *MockClient_BuildAndPush_Call {
	_c.Call.Return(run)
	return _c
}
