// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package deployermocks

import (
	"net/url"

	"github.com/robgonnella/minienv/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeployer creates a new instance of MockDeployer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeployer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeployer {
	mock := &MockDeployer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeployer is an autogenerated mock type for the Deployer type
type MockDeployer struct {
	mock.Mock
}

type MockDeployer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeployer) EXPECT() *MockDeployer_Expecter {
	return &MockDeployer_Expecter{mock: &_m.Mock}
}

// Active provides a mock function for the type MockDeployer
func (_mock *MockDeployer) Active() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Active")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDeployer_Active_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Active'
type MockDeployer_Active_Call struct {
	*mock.Call
}

// Active is a helper method to define mock.On call
func (_e *MockDeployer_Expecter) Active() *MockDeployer_Active_Call {
	return &MockDeployer_Active_Call{Call: _e.mock.On("Active")}
}

func (_c *MockDeployer_Active_Call) Run(run func()) *MockDeployer_Active_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployer_Active_Call) Return(b bool) *MockDeployer_Active_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDeployer_Active_Call) RunAndReturn(run func() bool) *MockDeployer_Active_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigField provides a mock function for the type MockDeployer
func (_mock *MockDeployer) ConfigField() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigField")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeployer_ConfigField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigField'
type MockDeployer_ConfigField_Call struct {
	*mock.Call
}

// ConfigField is a helper method to define mock.On call
func (_e *MockDeployer_Expecter) ConfigField() *MockDeployer_ConfigField_Call {
	return &MockDeployer_ConfigField_Call{Call: _e.mock.On("ConfigField")}
}

func (_c *MockDeployer_ConfigField_Call) Run(run func()) *MockDeployer_ConfigField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployer_ConfigField_Call) Return(s string) *MockDeployer_ConfigField_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeployer_ConfigField_Call) RunAndReturn(run func() string) *MockDeployer_ConfigField_Call {
	_c.Call.Return(run)
	return _c
}

// Deploy provides a mock function for the type MockDeployer
func (_mock *MockDeployer) Deploy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeployer_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type MockDeployer_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
func (_e *MockDeployer_Expecter) Deploy() *MockDeployer_Deploy_Call {
	return &MockDeployer_Deploy_Call{Call: _e.mock.On("Deploy")}
}

func (_c *MockDeployer_Deploy_Call) Run(run func()) *MockDeployer_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployer_Deploy_Call) Return(err error) *MockDeployer_Deploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeployer_Deploy_Call) RunAndReturn(run func() error) *MockDeployer_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockDeployer
func (_mock *MockDeployer) Destroy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeployer_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockDeployer_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockDeployer_Expecter) Destroy() *MockDeployer_Destroy_Call {
	return &MockDeployer_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockDeployer_Destroy_Call) Run(run func()) *MockDeployer_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployer_Destroy_Call) Return(err error) *MockDeployer_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeployer_Destroy_Call) RunAndReturn(run func() error) *MockDeployer_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockDeployer
func (_mock *MockDeployer) Init(project *config.ComposeProject) error {
	ret := _mock.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*config.ComposeProject) error); ok {
		r0 = returnFunc(project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeployer_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockDeployer_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - project *config.ComposeProject
func (_e *MockDeployer_Expecter) Init(project any) *MockDeployer_Init_Call {
	return &MockDeployer_Init_Call{Call: _e.mock.On("Init", project)}
}

func (_c *MockDeployer_Init_Call) Run(run func(project *config.ComposeProject)) *MockDeployer_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *config.ComposeProject
		if args[0] != nil {
			arg0 = args[0].(*config.ComposeProject)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeployer_Init_Call) Return(err error) *MockDeployer_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeployer_Init_Call) RunAndReturn(run func(project *config.ComposeProject) error) *MockDeployer_Init_Call {
	_c.Call.Return(run)
	return _c
}

// PublishedServiceUrls provides a mock function for the type MockDeployer
func (_mock *MockDeployer) PublishedServiceUrls() (map[string]url.URL, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PublishedServiceUrls")
	}

	var r0 map[string]url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]url.URL, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]url.URL); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeployer_PublishedServiceUrls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishedServiceUrls'
type MockDeployer_PublishedServiceUrls_Call struct {
	*mock.Call
}

// PublishedServiceUrls is a helper method to define mock.On call
func (_e *MockDeployer_Expecter) PublishedServiceUrls() *MockDeployer_PublishedServiceUrls_Call {
	return &MockDeployer_PublishedServiceUrls_Call{Call: _e.mock.On("PublishedServiceUrls")}
}

func (_c *MockDeployer_PublishedServiceUrls_Call) Run(run func()) *MockDeployer_PublishedServiceUrls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployer_PublishedServiceUrls_Call) Return(stringToURL map[string]url.URL, err error) *MockDeployer_PublishedServiceUrls_Call {
	_c.Call.Return(stringToURL, err)
	return _c
}

func (_c *MockDeployer_PublishedServiceUrls_Call) RunAndReturn(run func() (map[string]url.URL, error)) *MockDeployer_PublishedServiceUrls_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockDeployer
func (_mock *MockDeployer) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeployer_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockDeployer_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockDeployer_Expecter) String() *MockDeployer_String_Call {
	return &MockDeployer_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockDeployer_String_Call) Run(run func()) *MockDeployer_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployer_String_Call) Return(s string) *MockDeployer_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeployer_String_Call) RunAndReturn(run func() string) *MockDeployer_String_Call {
	_c.Call.Return(run)
	return _c
}
