// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package deployermocks

import (
	"context"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeployer creates a new instance of MockDeployer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeployer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeployer {
	mock := &MockDeployer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeployer is an autogenerated mock type for the Deployer type
type MockDeployer struct {
	mock.Mock
}

type MockDeployer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeployer) EXPECT() *MockDeployer_Expecter {
	return &MockDeployer_Expecter{mock: &_m.Mock}
}

// Deploy provides a mock function for the type MockDeployer
func (_mock *MockDeployer) Deploy(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeployer_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type MockDeployer_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeployer_Expecter) Deploy(ctx any) *MockDeployer_Deploy_Call {
	return &MockDeployer_Deploy_Call{Call: _e.mock.On("Deploy", ctx)}
}

func (_c *MockDeployer_Deploy_Call) Run(run func(ctx context.Context)) *MockDeployer_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeployer_Deploy_Call) Return(err error) *MockDeployer_Deploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeployer_Deploy_Call) RunAndReturn(run func(ctx context.Context) error) *MockDeployer_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockDeployer
func (_mock *MockDeployer) Destroy(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeployer_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockDeployer_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeployer_Expecter) Destroy(ctx any) *MockDeployer_Destroy_Call {
	return &MockDeployer_Destroy_Call{Call: _e.mock.On("Destroy", ctx)}
}

func (_c *MockDeployer_Destroy_Call) Run(run func(ctx context.Context)) *MockDeployer_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeployer_Destroy_Call) Return(err error) *MockDeployer_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeployer_Destroy_Call) RunAndReturn(run func(ctx context.Context) error) *MockDeployer_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockDeployer
func (_mock *MockDeployer) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeployer_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockDeployer_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeployer_Expecter) Init(ctx any) *MockDeployer_Init_Call {
	return &MockDeployer_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockDeployer_Init_Call) Run(run func(ctx context.Context)) *MockDeployer_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeployer_Init_Call) Return(err error) *MockDeployer_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeployer_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockDeployer_Init_Call {
	_c.Call.Return(run)
	return _c
}

// PublishedServiceUrls provides a mock function for the type MockDeployer
func (_mock *MockDeployer) PublishedServiceUrls(ctx context.Context) (map[string]url.URL, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PublishedServiceUrls")
	}

	var r0 map[string]url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]url.URL, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]url.URL); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeployer_PublishedServiceUrls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishedServiceUrls'
type MockDeployer_PublishedServiceUrls_Call struct {
	*mock.Call
}

// PublishedServiceUrls is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeployer_Expecter) PublishedServiceUrls(ctx any) *MockDeployer_PublishedServiceUrls_Call {
	return &MockDeployer_PublishedServiceUrls_Call{Call: _e.mock.On("PublishedServiceUrls", ctx)}
}

func (_c *MockDeployer_PublishedServiceUrls_Call) Run(run func(ctx context.Context)) *MockDeployer_PublishedServiceUrls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeployer_PublishedServiceUrls_Call) Return(stringToURL map[string]url.URL, err error) *MockDeployer_PublishedServiceUrls_Call {
	_c.Call.Return(stringToURL, err)
	return _c
}

func (_c *MockDeployer_PublishedServiceUrls_Call) RunAndReturn(run func(ctx context.Context) (map[string]url.URL, error)) *MockDeployer_PublishedServiceUrls_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockDeployer
func (_mock *MockDeployer) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeployer_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockDeployer_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockDeployer_Expecter) String() *MockDeployer_String_Call {
	return &MockDeployer_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockDeployer_String_Call) Run(run func()) *MockDeployer_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployer_String_Call) Return(s string) *MockDeployer_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeployer_String_Call) RunAndReturn(run func() string) *MockDeployer_String_Call {
	_c.Call.Return(run)
	return _c
}
