// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package publishingmocks

import (
	"context"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ServiceUrls provides a mock function for the type MockClient
func (_mock *MockClient) ServiceUrls(ctx context.Context, svcNames []string) (map[string]url.URL, error) {
	ret := _mock.Called(ctx, svcNames)

	if len(ret) == 0 {
		panic("no return value specified for ServiceUrls")
	}

	var r0 map[string]url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]url.URL, error)); ok {
		return returnFunc(ctx, svcNames)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]url.URL); ok {
		r0 = returnFunc(ctx, svcNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, svcNames)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ServiceUrls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceUrls'
type MockClient_ServiceUrls_Call struct {
	*mock.Call
}

// ServiceUrls is a helper method to define mock.On call
//   - ctx context.Context
//   - svcNames []string
func (_e *MockClient_Expecter) ServiceUrls(ctx any, svcNames any) *MockClient_ServiceUrls_Call {
	return &MockClient_ServiceUrls_Call{Call: _e.mock.On("ServiceUrls", ctx, svcNames)}
}

func (_c *MockClient_ServiceUrls_Call) Run(run func(ctx context.Context, svcNames []string)) *MockClient_ServiceUrls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ServiceUrls_Call) Return(stringToURL map[string]url.URL, err error) *MockClient_ServiceUrls_Call {
	_c.Call.Return(stringToURL, err)
	return _c
}

func (_c *MockClient_ServiceUrls_Call) RunAndReturn(run func(ctx context.Context, svcNames []string) (map[string]url.URL, error)) *MockClient_ServiceUrls_Call {
	_c.Call.Return(run)
	return _c
}
