name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        include:
          - ext: ""
          - ext: .exe
            good: windows
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-tooling
      - name: Build Binary for ${{ matrix.goos }}-${{ matrix.goarch }}"
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build \
          -ldflags="-s -w" \
          -trimpath \
          -o build/${{ github.event.repository.name }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} \
          cmd/minienv/main.go
